### PR TITLE
Allow `using` statements to access packages loaded within workspace

### PR DESCRIPTION
**Pull request by ZacLN**
I _think_ this is all that's needed on this side so that `using` statements will point to the 'live' code of packages that is being edited. Alongside the symbolserver store of packages I've added a new `workspacepackages` field which will be checked prior to the symbolserver list. It will be up to the user (e.g. the LanguageServerInstance) to ensure that this list is properly managed, I'll open a PR on the other side to discuss how this is managed.

Todo:

- [x] Add accessor function 

Example code:
```julia
using StaticLint, SymbolServer, CSTParser
using StaticLint: File, FileServer, loadfile, scopepass

server = FileServer(Dict(), Set(), deepcopy(SymbolServer.stdlibs), Dict{String,CSTParser.EXPR}());
f = loadfile(server, String(first(methods(CSTParser.eval)).file))
scopepass(f)
server.workspacepackages["CSTParser"] = f.cst.meta.scope.names["CSTParser"] #Load the local/live version of CSTParser

s = """
using CSTParser
ParseState
"""
f = File("none", s, CSTParser.parse(s, true), nothing, server)
f.root = f
scopepass(f)
f.cst
# FileH  27(26) new scope
#  Using  16(15)
#   USING  6(5)
#   CSTParser  10(9) Binding(CSTParser(1 refs)) * 
#  ParseState  11(10)  * 
```

### CODE REVIEW

**Comment by ZacLN** [comment]
@davidanthoff could you have  a look at this (and [this](https://github.com/julia-vscode/LanguageServer.jl/pull/562) on the LS side) now. Alongside whats described in first comment above there are some fixes for reference resolving (that were less apparent prior to this change).

**Comment by davidanthoff** [comment]
@ZacLN what is the next step here? Probably for you to clean up merge conflicts, and then I review it?

**Comment by ZacLN** [comment]
Should be good to merge now, lets see what the tests say.

**Comment by davidanthoff** [comment]
So main question is whether we try to put this in before Juliacon, or after? My sense is maybe after?

**Comment by davidanthoff** [comment]
@ZacLN so I tried to fix this, there were some typos, but now I'm stuck :)

**Comment by pfitzseb** [comment]
Tests should pass now. Would still be good if Zac can approve the PR though :)

**Review by pfitzseb — APPROVED** [review]

**Comment by ZacLN** [comment]
Yes looks good (`typof` was a deprecated function rather than a typo)

**Pull request merged**
