### PR TITLE
add support for Turing.model macro

### PR DESCRIPTION
**Pull request by ZacLN**

### CODE REVIEW

**Comment by ZacLN** [comment]
A general solution leads down the road to interpretation...

**Comment by aviatesk** [comment]
@ZacLN Zac, this is just for my reference, but is the reason why we should avoid interpreting code (which can expand macros) is that it leads to bad performance ?
I'm writing an essay about an analysis of code in general and wondering how the existence of macro makes it difficult to analyse code.

**Comment by ZacLN** [comment]
Hi, I haven't given too much thought to it yet -there are other priorities- but yes, I think it could be computationally intensive. There are also safety concerns around having the editor able to run arbitrary code, which would have to be handled carefully.

**Comment by aviatesk** [comment]
Fair enough, I can imagine computation would get complex and costly for example when an user has modified a macro and StaticLint.jl has to "re-expand" all its uses, etc.
A safety problem around code execution is also interesting.

Anyway thanks for your reply :)
Please let me know if you have another idea on this !

**Pull request merged**
