### PR TITLE
power up constant redef check

### PR DESCRIPTION
**Pull request by aviatesk**
So that our linter warns on:
- Screen Shot 2020-07-13 at 21 54 21
- Screen Shot 2020-07-13 at 21 54 47

### CODE REVIEW

**Comment by davidanthoff** [comment]
Post Juliacon stuff, right?

**Comment by pfitzseb** [comment]
Yes. Would probably make sense to use the "Next extension minor release" milestone here, no?

**Comment by aviatesk** [comment]
> Post Juliacon stuff, right?

yeah

**Comment by aviatesk** [comment]
@ZacLN can you review this ?

**Review by ZacLN — APPROVED** [review]

**Pull request merged**
