### PR TITLE
add char, bool and unsigned literal checks

### PR DESCRIPTION
**Pull request by laborg**
I'm not sure if the "counting-the-digits" approach for checking unsigned literals is viable but I couldn't find an example where this would backfire.

### CODE REVIEW

**Comment by ZacLN** [comment]
What happened to this? I didn't have a chance to look it through in detail but it seemed good

**Comment by davidanthoff** [comment]
I don't understand, actually... I didn't close it, and now I also can't reopen it?!?

**Comment by davidanthoff** [comment]
It says I can't reopen it because the branch was deleted? I also don't understand that because the branch was never in this repo, but only in the fork, so I could not have deleted it in the first place? @laborg, die you maybe delete the branch in your repo?

**Comment by ZacLN** [comment]
Lmaybe it was a pr against mine so got removed when that was deleted. I'll recreate it

**Comment by laborg** [comment]
> Lmaybe it was a pr against mine so got removed when that was deleted. I'll recreate it

Thats what I think what happend. I've already opened #194 instead

**Pull request closed without merging**
