### PR TITLE
a bit refactor (separated from #206)

### PR DESCRIPTION
**Pull request by aviatesk**

### CODE REVIEW

**Comment by aviatesk** [comment]
@ZacLN this PR is not urgent at all, but it would be great if you can approve this.

**Comment by aviatesk** [comment]
@ZacLN can we go forward with this ? Actually you already approved this in #206 , but I separated this part from it.

**Review by ZacLN — APPROVED** [review]

**Comment by ZacLN** [comment]
Note - I'm moving these PRs across to https://github.com/julia-vscode/StaticLint.jl/pull/203 as they get merged here

**Comment by aviatesk** [comment]
It's totally okay -- #203 would refactor many parts anyway.

**Pull request merged**
