### PR TITLE
add infrastructure for file-specific environments

### PR DESCRIPTION
**Pull request by ZacLN**
Currently has no effect but puts in place a mechnism to allow the server to specify what collection of SymbolStore cached packages are made available to a given file. For LanguageServer this means a workspace with multiple folders (packages) open could have the appropriate environments made available to each (and additional packages for test folders, etc). 

~Not for immediate merging.~
Ready, will require tagging

### CODE REVIEW

**Comment by davidanthoff** [comment]
We'll wait until we have 1.1 out, right?

**Review by davidanthoff — CHANGES_REQUESTED** [review]
We could include this in 1.2, right? If so, we just need a merge conflict resolution, I think.

**Comment by pfitzseb** [comment]
Ok, fixed the conflicts and tests pass locally, but @ZacLN should definitely have a look at this again before we merge :)

**Comment by ZacLN** [comment]
I think it's good to go

**Review by davidanthoff — APPROVED** [review]

**Pull request merged**
